// Base de datos de 22 alojamientos de Media Estancia (1 a 11 meses) en Paraguay
// Con coordenadas geográficas precisas, ratings, fotos HD y métricas WFH
window.PROPERTIES_DATA = [
    {
        id: "ZIL-301",
        title: "Penthouse de Diseño con Rooftop Privado & Parrilla",
        operation: "rent_monthly",
        propType: "apartment",
        category: "luxury",
        rating: 4.98,
        reviewCount: 47,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "A 350 m de Shopping Mariscal y Paseo Carmelitas",
        tier: "platinum",
        priceUSD: 1450,
        pricePYG: 11527500,
        currencyPrimary: "USD",
        expensesPYG: 1200000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 500,
        utilitiesMonthlyUSD: 75,
        cleaningFeeUSD: 50,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Villa Morra",
        address: "Av. Mariscal López c/ Senador Long",
        coordinates: [-25.2938, -57.5794],
        bedrooms: 3,
        bathrooms: 3,
        bedsCount: 3,
        parkingSpots: 2,
        builtAreaM2: 240,
        totalAreaM2: 280,
        badge: "Recomendación del viajero",
        amenities: ["pool", "gym", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "terrace", "generator", "jacuzzi", "elevator", "smart_home", "coworking"],
        wfhSetup: "Escritorio ergonómico con silla Herman Miller, router WiFi 6 dual-band y tomas USB-C",
        advertiser: {
            name: "Carlos Benítez",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 15 min",
            phone: "+595981123456",
            whatsapp: "595981123456",
            avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=150&q=80"
        },
        description: "Exclusivo penthouse con terraza panorámica, quincho gourmet propio y piscina privada. Ideal para estancias de 3 a 11 meses.",
        images: [
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-302",
        title: "Studio Ejecutivo en Torre Santa Teresa con Rooftop Pool",
        operation: "rent_monthly",
        propType: "apartment",
        category: "pool",
        rating: 4.96,
        reviewCount: 38,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "A 200 m de Paseo La Galería y WTC Asunción",
        tier: "platinum",
        priceUSD: 1150,
        pricePYG: 9142500,
        currencyPrimary: "USD",
        expensesPYG: 850000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 500,
        utilitiesMonthlyUSD: 60,
        cleaningFeeUSD: 40,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Santa Teresa",
        address: "Av. Santa Teresa c/ Herminio Maldonado",
        coordinates: [-25.2861, -57.5623],
        bedrooms: 1,
        bathrooms: 1,
        bedsCount: 1,
        parkingSpots: 1,
        builtAreaM2: 65,
        totalAreaM2: 75,
        badge: "Recomendación del viajero",
        amenities: ["pool", "gym", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "terrace", "coworking", "elevator", "smart_home"],
        wfhSetup: "Escritorio con monitor externo de 27 pulgadas, teclado Bluetooth y fibra 500Mbps",
        advertiser: {
            name: "Fernando Giménez",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 5 min",
            phone: "+595971987654",
            whatsapp: "595971987654",
            avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80"
        },
        description: "Studio amoblado con diseño escandinavo a pasos del World Trade Center. Balcón con parrilla y gimnasio en la torre.",
        images: [
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-303",
        title: "Loft Minimalista en Polo Gastronómico Denis Roa",
        operation: "rent_monthly",
        propType: "apartment",
        category: "wfh",
        rating: 4.93,
        reviewCount: 29,
        guestFavorite: false,
        superhost: true,
        distanceHighlight: "En el polo gastronómico Denis Roa / Lillo",
        tier: "gold",
        priceUSD: 950,
        pricePYG: 7552500,
        currencyPrimary: "USD",
        expensesPYG: 650000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 400,
        utilitiesMonthlyUSD: 55,
        cleaningFeeUSD: 35,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Ycuá Satí",
        address: "Av. Denis Roa c/ Lillo",
        coordinates: [-25.2982, -57.5647],
        bedrooms: 1,
        bathrooms: 1,
        bedsCount: 1,
        parkingSpots: 1,
        builtAreaM2: 58,
        totalAreaM2: 68,
        badge: "WiFi 400M • A Estrenar",
        amenities: ["pool", "gym", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "terrace", "elevator", "smart_home"],
        wfhSetup: "Espacio de trabajo integrado con iluminación regulable y vista abierta",
        advertiser: {
            name: "María José Duarte",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 10 min",
            phone: "+595982654321",
            whatsapp: "595982654321",
            avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80"
        },
        description: "Moderno loft con cama queen, Smart TV 55', cocina de inducción y laundry en el edificio. Ideal para 3 a 6 meses.",
        images: [
            "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1502005229762-ee1b2b8ab98f?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-304",
        title: "Residencia Campestre en Club de Campo Surubi'i",
        operation: "rent_monthly",
        propType: "house",
        category: "views",
        rating: 4.99,
        reviewCount: 22,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "A 12 min del Aeropuerto Silvio Pettirossi",
        tier: "platinum",
        priceUSD: 2200,
        pricePYG: 17490000,
        currencyPrimary: "USD",
        expensesPYG: 1500000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 500,
        utilitiesMonthlyUSD: 110,
        cleaningFeeUSD: 80,
        department: "Central",
        city: "Mariano Roque Alonso",
        neighborhood: "Surubi'i",
        address: "Condominio Club de Campo Surubi'i",
        coordinates: [-25.2155, -57.5458],
        bedrooms: 4,
        bathrooms: 4,
        bedsCount: 5,
        parkingSpots: 4,
        builtAreaM2: 380,
        totalAreaM2: 1200,
        badge: "Barrio Cerrado • WiFi 500M",
        amenities: ["pool", "gym", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "garden", "generator", "sports_court"],
        wfhSetup: "Estudio privado independiente con biblioteca y fibra simétrica",
        advertiser: {
            name: "Ing. Roberto Alarcón",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 30 min",
            phone: "+595981556677",
            whatsapp: "595981556677",
            avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80"
        },
        description: "Casa de descanso y trabajo en Surubi'i. Gran jardín con piscina, quincho con tatakua y generador automático.",
        images: [
            "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-305",
        title: "Villa con Vista al Lago & Piscina en San Bernardino",
        operation: "rent_monthly",
        propType: "house",
        category: "lake",
        rating: 4.97,
        reviewCount: 35,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "A 300 m de la playa del Lago Ypacaraí",
        tier: "platinum",
        priceUSD: 1850,
        pricePYG: 14707500,
        currencyPrimary: "USD",
        expensesPYG: 0,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 300,
        utilitiesMonthlyUSD: 90,
        cleaningFeeUSD: 60,
        department: "Cordillera",
        city: "San Bernardino",
        neighborhood: "San Bernardino",
        address: "Av. Luis F. Vache c/ Mbocayaty",
        coordinates: [-25.3097, -57.2965],
        bedrooms: 4,
        bathrooms: 4,
        bedsCount: 6,
        parkingSpots: 3,
        builtAreaM2: 310,
        totalAreaM2: 900,
        badge: "Recomendación del viajero",
        amenities: ["pool", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "garden", "generator", "sports_court"],
        wfhSetup: "Terraza con mesa de trabajo con vista panorámica al lago Ypacaraí",
        advertiser: {
            name: "Rodrigo Alcaraz",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 10 min",
            phone: "+595991443322",
            whatsapp: "595991443322",
            avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80"
        },
        description: "Villa para estancias medias de trabajo y relax a solo 300m de la playa de San Ber.",
        images: [
            "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-306",
        title: "Dúplex de 3 Dormitorios con Jardín y Parrilla en Recoleta",
        operation: "rent_monthly",
        propType: "duplex",
        category: "pet_friendly",
        rating: 4.94,
        reviewCount: 19,
        guestFavorite: false,
        superhost: true,
        distanceHighlight: "A 400 m de Superseis Denis Roa",
        tier: "gold",
        priceUSD: 1100,
        pricePYG: 8745000,
        currencyPrimary: "USD",
        expensesPYG: 0,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 400,
        utilitiesMonthlyUSD: 65,
        cleaningFeeUSD: 45,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Recoleta",
        address: "Dr. Morra c/ Andrade",
        coordinates: [-25.3015, -57.5752],
        bedrooms: 3,
        bathrooms: 3,
        bedsCount: 4,
        parkingSpots: 2,
        builtAreaM2: 190,
        totalAreaM2: 240,
        badge: "Superanfitrión",
        amenities: ["pool", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "garden"],
        wfhSetup: "Habitación secundaria con 2 escritorios profesionales",
        advertiser: {
            name: "Gustavo Caballero",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 20 min",
            phone: "+595981556677",
            whatsapp: "595981556677",
            avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80"
        },
        description: "Dúplex en zona residencial arbolada de Recoleta con patio privado y parrilla techada.",
        images: [
            "https://images.unsplash.com/photo-1598228723793-52759bba239c?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-307",
        title: "Apartamento Escandinavo en Torre Skytower Santa Teresa",
        operation: "rent_monthly",
        propType: "apartment",
        category: "luxury",
        rating: 4.97,
        reviewCount: 31,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "Frente al Sheraton y Paseo La Galería",
        tier: "platinum",
        priceUSD: 1350,
        pricePYG: 10732500,
        currencyPrimary: "USD",
        expensesPYG: 950000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 600,
        utilitiesMonthlyUSD: 70,
        cleaningFeeUSD: 45,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Santa Teresa",
        address: "Av. Santa Teresa esq. Coronel Cabrera",
        coordinates: [-25.2842, -57.5589],
        bedrooms: 2,
        bathrooms: 2,
        bedsCount: 2,
        parkingSpots: 1,
        builtAreaM2: 95,
        totalAreaM2: 110,
        badge: "Recomendación del viajero",
        amenities: ["pool", "gym", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "terrace", "elevator", "smart_home", "coworking"],
        wfhSetup: "Home office panorámico piso 18 con vista al skyline",
        advertiser: {
            name: "Lorena Valiente",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 10 min",
            phone: "+595983112233",
            whatsapp: "595983112233",
            avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80"
        },
        description: "Piso alto con balcón vidriado, acabados de mármol y acceso a spa, piscina infinita y coworking en el edificio.",
        images: [
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-308",
        title: "Casa de Autor con Piscina y Jardín Zen en Las Lomas",
        operation: "rent_monthly",
        propType: "house",
        category: "pool",
        rating: 4.99,
        reviewCount: 16,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "A 3 min de Shopping del Sol",
        tier: "platinum",
        priceUSD: 2400,
        pricePYG: 19080000,
        currencyPrimary: "USD",
        expensesPYG: 0,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 500,
        utilitiesMonthlyUSD: 120,
        cleaningFeeUSD: 90,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Las Lomas",
        address: "Guido Spano c/ San Rafael",
        coordinates: [-25.2891, -57.5712],
        bedrooms: 3,
        bathrooms: 4,
        bedsCount: 4,
        parkingSpots: 3,
        builtAreaM2: 320,
        totalAreaM2: 600,
        badge: "Recomendación del viajero",
        amenities: ["pool", "gym", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "garden", "generator"],
        wfhSetup: "Oficina privada vidriada con vista al jardín y estanque",
        advertiser: {
            name: "Arq. Marcelo Rivas",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 15 min",
            phone: "+595981778899",
            whatsapp: "595981778899",
            avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80"
        },
        description: "Obra arquitectónica contemporánea con luz natural cenital, piscina templada y parrilla automatizada.",
        images: [
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-309",
        title: "Studio Boho Chic en Barrio Manorá",
        operation: "rent_monthly",
        propType: "apartment",
        category: "wfh",
        rating: 4.91,
        reviewCount: 42,
        guestFavorite: false,
        superhost: true,
        distanceHighlight: "A pasos de Av. San Martín y restaurantes",
        tier: "gold",
        priceUSD: 850,
        pricePYG: 6757500,
        currencyPrimary: "USD",
        expensesPYG: 500000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 400,
        utilitiesMonthlyUSD: 50,
        cleaningFeeUSD: 35,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Manorá",
        address: "Moisés Bertoni c/ Saraví",
        coordinates: [-25.2915, -57.5835],
        bedrooms: 1,
        bathrooms: 1,
        bedsCount: 1,
        parkingSpots: 1,
        builtAreaM2: 48,
        totalAreaM2: 55,
        badge: "Superanfitrión",
        amenities: ["pool", "furnished", "laundry", "pet_friendly", "security", "garage", "air_conditioning", "elevator"],
        wfhSetup: "Rincón de trabajo con escritorio de madera maciza y luz natural",
        advertiser: {
            name: "Camila Insfrán",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 5 min",
            phone: "+595982334455",
            whatsapp: "595982334455",
            avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80"
        },
        description: "Studio cálido con balcón francés, ideal para nómadas que buscan tranquilidad y cercanía al polo gastronómico.",
        images: [
            "https://images.unsplash.com/photo-1502005229762-ee1b2b8ab98f?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1540518614846-7ede433c4ef0?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-310",
        title: "Departamento de 2 Dormitorios con Terraza en Mburucuyá",
        operation: "rent_monthly",
        propType: "apartment",
        category: "views",
        rating: 4.95,
        reviewCount: 26,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "A 400 m de Parque de la Salud",
        tier: "platinum",
        priceUSD: 1200,
        pricePYG: 9540000,
        currencyPrimary: "USD",
        expensesPYG: 800000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 500,
        utilitiesMonthlyUSD: 65,
        cleaningFeeUSD: 45,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Mburucuyá",
        address: "Av. Santísima Trinidad c/ Julio Correa",
        coordinates: [-25.2758, -57.5684],
        bedrooms: 2,
        bathrooms: 2,
        bedsCount: 2,
        parkingSpots: 1,
        builtAreaM2: 88,
        totalAreaM2: 102,
        badge: "Recomendación del viajero",
        amenities: ["pool", "gym", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "terrace", "elevator", "smart_home"],
        wfhSetup: "Escritorio dual en living con conexión LAN directa",
        advertiser: {
            name: "Diego Ortiz",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 15 min",
            phone: "+595981990011",
            whatsapp: "595981990011",
            avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80"
        },
        description: "Piso 12 con vista abierta al río y al Parque de la Salud. Edificio con rooftop, gimnasio y quincho.",
        images: [
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-311",
        title: "Chalet Moderno con Parrilla en Los Laureles",
        operation: "rent_monthly",
        propType: "house",
        category: "quincho",
        rating: 4.92,
        reviewCount: 21,
        guestFavorite: false,
        superhost: true,
        distanceHighlight: "Barrio residencial tranquilo y arbolado",
        tier: "gold",
        priceUSD: 1300,
        pricePYG: 10335000,
        currencyPrimary: "USD",
        expensesPYG: 0,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 400,
        utilitiesMonthlyUSD: 70,
        cleaningFeeUSD: 50,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Los Laureles",
        address: "R.I. 6 Boquerón c/ Facundo Machaín",
        coordinates: [-25.3112, -57.5705],
        bedrooms: 3,
        bathrooms: 2,
        bedsCount: 3,
        parkingSpots: 2,
        builtAreaM2: 175,
        totalAreaM2: 360,
        badge: "Superanfitrión",
        amenities: ["pool", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "garden"],
        wfhSetup: "Home office en planta baja con entrada de luz directa",
        advertiser: {
            name: "Sofía Argaña",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 20 min",
            phone: "+595984223344",
            whatsapp: "595984223344",
            avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80"
        },
        description: "Casa estilo chalet de una planta con jardín íntimo, piscina y quincho con parrilla tradicional.",
        images: [
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-312",
        title: "Loft Industrial con Balcón en Barrio Herrera",
        operation: "rent_monthly",
        propType: "apartment",
        category: "wfh",
        rating: 4.89,
        reviewCount: 18,
        guestFavorite: false,
        superhost: false,
        distanceHighlight: "A 5 min de la Municipalidad de Asunción",
        tier: "gold",
        priceUSD: 780,
        pricePYG: 6201000,
        currencyPrimary: "USD",
        expensesPYG: 450000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 350,
        utilitiesMonthlyUSD: 45,
        cleaningFeeUSD: 30,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Herrera",
        address: "Av. Mariscal López c/ Madame Lynch",
        coordinates: [-25.3045, -57.5532],
        bedrooms: 1,
        bathrooms: 1,
        bedsCount: 1,
        parkingSpots: 1,
        builtAreaM2: 52,
        totalAreaM2: 60,
        badge: "Excelente Precio",
        amenities: ["furnished", "laundry", "security", "garage", "air_conditioning", "elevator"],
        wfhSetup: "Mesa alta de trabajo tipo coworking con banquetas acolchadas",
        advertiser: {
            name: "Lucas Bogado",
            agency: "Host Zilla",
            verified: true,
            responseTime: "< 30 min",
            phone: "+595985112233",
            whatsapp: "595985112233",
            avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80"
        },
        description: "Loft con vigas vistas de hormigón, cocina integrada con barra desayunadora y balcón al frente.",
        images: [
            "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1502005229762-ee1b2b8ab98f?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-313",
        title: "Apartamento de Lujo con Vista a la Bahía de Asunción",
        operation: "rent_monthly",
        propType: "apartment",
        category: "views",
        rating: 4.96,
        reviewCount: 33,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "Frente a la Costanera y Palacio de López",
        tier: "platinum",
        priceUSD: 1100,
        pricePYG: 8745000,
        currencyPrimary: "USD",
        expensesPYG: 700000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 500,
        utilitiesMonthlyUSD: 60,
        cleaningFeeUSD: 40,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Centro Histórico",
        address: "Av. Costanera José Asunción Flores",
        coordinates: [-25.2798, -57.6354],
        bedrooms: 2,
        bathrooms: 2,
        bedsCount: 2,
        parkingSpots: 1,
        builtAreaM2: 85,
        totalAreaM2: 98,
        badge: "Recomendación del viajero",
        amenities: ["pool", "gym", "furnished", "laundry", "security", "quincho", "garage", "air_conditioning", "terrace", "elevator"],
        wfhSetup: "Balcón acondicionado para trabajar con vista directa a la bahía y atardeceres",
        advertiser: {
            name: "Valeria Cantero",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 10 min",
            phone: "+595981665544",
            whatsapp: "595981665544",
            avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80"
        },
        description: "Ubicación céntrica con vistas impresionantes al río Paraguay y atardeceres de postal.",
        images: [
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-314",
        title: "Condominio Lakefront con Muelle Privado en San Bernardino",
        operation: "rent_monthly",
        propType: "apartment",
        category: "lake",
        rating: 4.98,
        reviewCount: 40,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "Frente al lago Ypacaraí con acceso a kayak",
        tier: "platinum",
        priceUSD: 1600,
        pricePYG: 12720000,
        currencyPrimary: "USD",
        expensesPYG: 900000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 400,
        utilitiesMonthlyUSD: 80,
        cleaningFeeUSD: 50,
        department: "Cordillera",
        city: "San Bernardino",
        neighborhood: "Ciervo Cuá",
        address: "Ruta San Ber - Luque km 38",
        coordinates: [-25.3214, -57.3115],
        bedrooms: 3,
        bathrooms: 2,
        bedsCount: 4,
        parkingSpots: 2,
        builtAreaM2: 140,
        totalAreaM2: 170,
        badge: "Recomendación del viajero",
        amenities: ["pool", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "terrace", "garden", "sports_court"],
        wfhSetup: "Galería exterior climatizada con mesa para reuniones virtuales frente al agua",
        advertiser: {
            name: "Enrique Saguier",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 5 min",
            phone: "+595982887766",
            whatsapp: "595982887766",
            avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80"
        },
        description: "Exclusivo departamento en condominio privado frente al lago Ypacaraí con muelle y piscina infinity.",
        images: [
            "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-315",
        title: "Cabaña de Montaña con Vista al Valle en Altos del Lago",
        operation: "rent_monthly",
        propType: "house",
        category: "views",
        rating: 4.95,
        reviewCount: 15,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "A 8 min de San Bernardino",
        tier: "gold",
        priceUSD: 1050,
        pricePYG: 8347500,
        currencyPrimary: "USD",
        expensesPYG: 0,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 300,
        utilitiesMonthlyUSD: 60,
        cleaningFeeUSD: 45,
        department: "Cordillera",
        city: "Altos",
        neighborhood: "Altos",
        address: "Cerro de Altos c/ Mirador",
        coordinates: [-25.2654, -57.2589],
        bedrooms: 2,
        bathrooms: 2,
        bedsCount: 3,
        parkingSpots: 2,
        builtAreaM2: 120,
        totalAreaM2: 800,
        badge: "Recomendación del viajero",
        amenities: ["pool", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "garden", "terrace"],
        wfhSetup: "Deck exterior techado con wifi de largo alcance",
        advertiser: {
            name: "Belén Morínigo",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 15 min",
            phone: "+595983445566",
            whatsapp: "595983445566",
            avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80"
        },
        description: "Cabaña con deck voladizo y vistas infinitas a la serranía y al lago Ypacaraí. Clima fresco y silencio absoluto.",
        images: [
            "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-316",
        title: "Piso Corporativo en Edificio Plaza Mayor Luque",
        operation: "rent_monthly",
        propType: "apartment",
        category: "wfh",
        rating: 4.88,
        reviewCount: 14,
        guestFavorite: false,
        superhost: true,
        distanceHighlight: "A 5 min del Aeropuerto y Conmebol",
        tier: "gold",
        priceUSD: 750,
        pricePYG: 5962500,
        currencyPrimary: "USD",
        expensesPYG: 400000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 500,
        utilitiesMonthlyUSD: 45,
        cleaningFeeUSD: 30,
        department: "Central",
        city: "Luque",
        neighborhood: "Zona Conmebol",
        address: "Av. Sudamericana c/ Autopista",
        coordinates: [-25.2612, -57.5145],
        bedrooms: 1,
        bathrooms: 1,
        bedsCount: 1,
        parkingSpots: 1,
        builtAreaM2: 54,
        totalAreaM2: 62,
        badge: "Cerca Aeropuerto",
        amenities: ["pool", "gym", "furnished", "laundry", "security", "quincho", "garage", "air_conditioning", "elevator", "smart_home"],
        wfhSetup: "Setup corporativo completo con monitor y conexión simétrica",
        advertiser: {
            name: "Esteban Melgarejo",
            agency: "Host Zilla",
            verified: true,
            responseTime: "< 20 min",
            phone: "+595981001122",
            whatsapp: "595981001122",
            avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80"
        },
        description: "Ubicación estratégica cerca del aeropuerto Silvio Pettirossi y centros de convenciones.",
        images: [
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-317",
        title: "Apartamento Costanera con Vista al Río Paraná en Encarnación",
        operation: "rent_monthly",
        propType: "apartment",
        category: "lake",
        rating: 4.97,
        reviewCount: 28,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "Frente a Playa San José y Costanera",
        tier: "platinum",
        priceUSD: 890,
        pricePYG: 7075500,
        currencyPrimary: "USD",
        expensesPYG: 500000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 400,
        utilitiesMonthlyUSD: 50,
        cleaningFeeUSD: 35,
        department: "Itapúa",
        city: "Encarnación",
        neighborhood: "Costanera Playa San José",
        address: "Av. Costanera República del Paraguay",
        coordinates: [-27.3325, -55.8678],
        bedrooms: 2,
        bathrooms: 2,
        bedsCount: 3,
        parkingSpots: 1,
        builtAreaM2: 78,
        totalAreaM2: 90,
        badge: "Recomendación del viajero",
        amenities: ["pool", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "terrace", "elevator"],
        wfhSetup: "Escritorio frente al ventanal con vista panorámica a la playa y puente internacional",
        advertiser: {
            name: "Federico Hrisuk",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 10 min",
            phone: "+595975112233",
            whatsapp: "595975112233",
            avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80"
        },
        description: "Hermoso departamento frente al río Paraná. Caminatas sobre la costanera y gastronomía al lado.",
        images: [
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-318",
        title: "Mansión en Paraná Country Club de Hernandarias / CDE",
        operation: "rent_monthly",
        propType: "house",
        category: "luxury",
        rating: 4.99,
        reviewCount: 12,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "Dentro del Paraná Country Club con campo de golf",
        tier: "platinum",
        priceUSD: 2800,
        pricePYG: 22260000,
        currencyPrimary: "USD",
        expensesPYG: 1800000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 600,
        utilitiesMonthlyUSD: 150,
        cleaningFeeUSD: 100,
        department: "Alto Paraná",
        city: "Hernandarias",
        neighborhood: "Paraná Country Club",
        address: "Av. Principal Paraná Country Club",
        coordinates: [-25.4412, -54.6321],
        bedrooms: 4,
        bathrooms: 5,
        bedsCount: 5,
        parkingSpots: 4,
        builtAreaM2: 450,
        totalAreaM2: 1500,
        badge: "Recomendación del viajero",
        amenities: ["pool", "gym", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "garden", "generator", "sports_court", "jacuzzi"],
        wfhSetup: "Estudio corporativo de doble altura con sala de conferencias privada",
        advertiser: {
            name: "Dra. Patricia Scheid",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 15 min",
            phone: "+595983778899",
            whatsapp: "595983778899",
            avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80"
        },
        description: "Máximo confort y seguridad en el condominio más exclusivo del este del país. Piscina climatizada y golf.",
        images: [
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-319",
        title: "Dúplex de Vanguardia con Piscina Propia en Fernando de la Mora",
        operation: "rent_monthly",
        propType: "duplex",
        category: "pool",
        rating: 4.90,
        reviewCount: 20,
        guestFavorite: false,
        superhost: true,
        distanceHighlight: "Zona Norte / Límite con Asunción",
        tier: "gold",
        priceUSD: 850,
        pricePYG: 6757500,
        currencyPrimary: "USD",
        expensesPYG: 0,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 400,
        utilitiesMonthlyUSD: 50,
        cleaningFeeUSD: 35,
        department: "Central",
        city: "Fernando de la Mora",
        neighborhood: "Zona Norte",
        address: "Soldado Ovelar c/ Mcal. Estigarribia",
        coordinates: [-25.3218, -57.5412],
        bedrooms: 3,
        bathrooms: 3,
        bedsCount: 3,
        parkingSpots: 2,
        builtAreaM2: 160,
        totalAreaM2: 200,
        badge: "Superanfitrión",
        amenities: ["pool", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "garden"],
        wfhSetup: "Espacio de trabajo privado con escritorio doble",
        advertiser: {
            name: "Marcos Centurión",
            agency: "Host Zilla",
            verified: true,
            responseTime: "< 25 min",
            phone: "+595982112233",
            whatsapp: "595982112233",
            avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80"
        },
        description: "Dúplex a estrenar con patio privado, piscina tipo plunge y quincho con parrilla.",
        images: [
            "https://images.unsplash.com/photo-1598228723793-52759bba239c?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-320",
        title: "Studio Nórdico con Balcón en Carmelitas",
        operation: "rent_monthly",
        propType: "apartment",
        category: "wfh",
        rating: 4.95,
        reviewCount: 37,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "A 100 m del Paseo Carmelitas",
        tier: "platinum",
        priceUSD: 990,
        pricePYG: 7870500,
        currencyPrimary: "USD",
        expensesPYG: 600000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 500,
        utilitiesMonthlyUSD: 55,
        cleaningFeeUSD: 35,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Las Lomas / Carmelitas",
        address: "Av. España c/ Malutín",
        coordinates: [-25.2905, -57.5742],
        bedrooms: 1,
        bathrooms: 1,
        bedsCount: 1,
        parkingSpots: 1,
        builtAreaM2: 55,
        totalAreaM2: 64,
        badge: "Recomendación del viajero",
        amenities: ["pool", "gym", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "elevator", "smart_home"],
        wfhSetup: "Escritorio gamer ergonómico con silla de respaldo alto y fibra 500M",
        advertiser: {
            name: "Sebastián Caniza",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 5 min",
            phone: "+595981334466",
            whatsapp: "595981334466",
            avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80"
        },
        description: "El departamento perfecto para teletrabajar en el corazón de Carmelitas. Bares, cafés y shopping a pie.",
        images: [
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1502005229762-ee1b2b8ab98f?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-321",
        title: "Penthouse con Piscina Infinity en Eje Santa Teresa",
        operation: "rent_monthly",
        propType: "apartment",
        category: "luxury",
        rating: 4.99,
        reviewCount: 45,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "Piso 22 con vista 360° a toda Asunción",
        tier: "platinum",
        priceUSD: 2100,
        pricePYG: 16695000,
        currencyPrimary: "USD",
        expensesPYG: 1500000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 1000,
        utilitiesMonthlyUSD: 100,
        cleaningFeeUSD: 70,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Santa Teresa",
        address: "Av. Santa Teresa c/ Denis Roa",
        coordinates: [-25.2855, -57.5610],
        bedrooms: 3,
        bathrooms: 4,
        bedsCount: 3,
        parkingSpots: 2,
        builtAreaM2: 260,
        totalAreaM2: 310,
        badge: "Recomendación del viajero",
        amenities: ["pool", "gym", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "terrace", "generator", "jacuzzi", "elevator", "smart_home", "coworking"],
        wfhSetup: "Oficina ejecutiva con fibra de 1 Gbps simétrica y sala de streaming",
        advertiser: {
            name: "Lic. Andrea Benítez",
            agency: "Superanfitrión Zilla",
            verified: true,
            responseTime: "< 5 min",
            phone: "+595981774411",
            whatsapp: "595981774411",
            avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80"
        },
        description: "El penthouse más imponente de Santa Teresa. Terraza con piscina infinita privada, quincho cerrado y spa.",
        images: [
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-322",
        title: "Apartamento Botánico en San Lorenzo / Zona Shopping Pinedo",
        operation: "rent_monthly",
        propType: "apartment",
        category: "pet_friendly",
        rating: 4.87,
        reviewCount: 16,
        guestFavorite: false,
        superhost: false,
        distanceHighlight: "A 300 m de Shopping Pinedo y UNA",
        tier: "gold",
        priceUSD: 690,
        pricePYG: 5485500,
        currencyPrimary: "USD",
        expensesPYG: 350000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 350,
        utilitiesMonthlyUSD: 40,
        cleaningFeeUSD: 25,
        department: "Central",
        city: "San Lorenzo",
        neighborhood: "Pinedo / UNA",
        address: "Av. Mcal. López c/ Laguna Grande",
        coordinates: [-25.3341, -57.5189],
        bedrooms: 2,
        bathrooms: 1,
        bedsCount: 2,
        parkingSpots: 1,
        builtAreaM2: 68,
        totalAreaM2: 76,
        badge: "Tarifa Accesible",
        amenities: ["pool", "furnished", "laundry", "pet_friendly", "security", "garage", "air_conditioning", "elevator"],
        wfhSetup: "Escritorio compacto con luz regulable y silla ergonómica",
        advertiser: {
            name: "Matías Rojas",
            agency: "Host Zilla",
            verified: true,
            responseTime: "< 20 min",
            phone: "+595982998877",
            whatsapp: "595982998877",
            avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80"
        },
        description: "Alojamiento amoblado muy luminoso a metros de Pinedo Shopping y la Universidad Nacional.",
        images: [
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80"
        ]
    }
];
