// Base de datos de alojamientos de Media Estancia (1 a 11 meses) en Paraguay
// Con metadatos completos estilo Airbnb Homes (Ratings, Categorías, Superanfitrión, WiFi 500M)
window.PROPERTIES_DATA = [
    {
        id: "ZIL-301",
        title: "Penthouse de Diseño con Rooftop Privado & Parrilla",
        operation: "rent_monthly",
        propType: "apartment",
        category: "luxury", // 'pool', 'wfh', 'lake', 'views', 'luxury', 'pet_friendly'
        rating: 4.98,
        reviewCount: 47,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "A 350 m de Shopping Mariscal y Paseo Carmelitas",
        tier: "platinum",
        priceUSD: 1450, // Tarifa base mensual
        pricePYG: 11527500,
        currencyPrimary: "USD",
        expensesPYG: 1200000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 500,
        utilitiesMonthlyUSD: 75,
        cleaningFeeUSD: 50,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Villa Morra",
        address: "Av. Mariscal López c/ Senador Long",
        coordinates: [-25.2938, -57.5794],
        bedrooms: 3,
        bathrooms: 3,
        bedsCount: 3,
        parkingSpots: 2,
        builtAreaM2: 240,
        totalAreaM2: 280,
        yearBuilt: 2023,
        badge: "Recomendación del viajero",
        acceptsCheRogaPora: false,
        bankCreditEligible: false,
        amenities: ["pool", "gym", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "terrace", "generator", "jacuzzi", "elevator", "smart_home", "coworking"],
        wfhSetup: "Escritorio ergonómico con silla Herman Miller, router WiFi 6 dual-band y tomas USB-C",
        advertiser: {
            name: "Carlos Benítez",
            agency: "Superanfitrión Zilla",
            type: "verified_agency",
            verified: true,
            responseTime: "< 15 min",
            phone: "+595981123456",
            whatsapp: "595981123456",
            avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=150&q=80"
        },
        description: "Exclusivo penthouse diseñado para ejecutivos y nómadas digitales. Cuenta con terraza privada con quincho gourmet, piscina privada, espacio de coworking integrado, cocina equipada con lavavajillas y cerradura digital inteligente con clave temporal.",
        nearbyPoints: [
            { name: "Paseo La Galería", distance: "800 m", time: "2 min en auto" },
            { name: "Shopping Mariscal", distance: "350 m", time: "4 min a pie" },
            { name: "Café Juan Valdez / Starbucks", distance: "200 m", time: "2 min a pie" }
        ],
        images: [
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-302",
        title: "Studio Ejecutivo en Torre Santa Teresa con Rooftop Pool",
        operation: "rent_monthly",
        propType: "apartment",
        category: "pool",
        rating: 4.96,
        reviewCount: 38,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "A 200 m de Paseo La Galería y WTC Asunción",
        tier: "platinum",
        priceUSD: 1150,
        pricePYG: 9142500,
        currencyPrimary: "USD",
        expensesPYG: 850000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 500,
        utilitiesMonthlyUSD: 60,
        cleaningFeeUSD: 40,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Santa Teresa",
        address: "Av. Santa Teresa c/ Herminio Maldonado",
        coordinates: [-25.2861, -57.5623],
        bedrooms: 1,
        bathrooms: 1,
        bedsCount: 1,
        parkingSpots: 1,
        builtAreaM2: 65,
        totalAreaM2: 75,
        yearBuilt: 2022,
        badge: "Recomendación del viajero",
        acceptsCheRogaPora: false,
        bankCreditEligible: false,
        amenities: ["pool", "gym", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "terrace", "coworking", "elevator", "smart_home"],
        wfhSetup: "Escritorio con monitor externo de 27 pulgadas, teclado/mouse Bluetooth y fibra 500Mbps",
        advertiser: {
            name: "Fernando Giménez",
            agency: "Superanfitrión Zilla",
            type: "verified_agency",
            verified: true,
            responseTime: "< 5 min",
            phone: "+595971987654",
            whatsapp: "595971987654",
            avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80"
        },
        description: "Studio totalmente amoblado con diseño escandinavo a pasos del World Trade Center. Balcón con parrilla privada, cocina con electrodomésticos empotrados, torre con gimnasio de última generación, piscina en piso 24 y sala de reuniones.",
        nearbyPoints: [
            { name: "World Trade Center Asunción", distance: "350 m", time: "4 min a pie" },
            { name: "Paseo La Galería", distance: "200 m", time: "2 min a pie" },
            { name: "Shopping del Sol", distance: "500 m", time: "5 min a pie" }
        ],
        images: [
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1540518614846-7ede433c4ef0?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-303",
        title: "Loft Minimalista con Balcón y Vista al Eje Corporativo",
        operation: "rent_monthly",
        propType: "apartment",
        category: "wfh",
        rating: 4.93,
        reviewCount: 29,
        guestFavorite: false,
        superhost: true,
        distanceHighlight: "En el polo gastronómico Denis Roa / Lillo",
        tier: "gold",
        priceUSD: 950,
        pricePYG: 7552500,
        currencyPrimary: "USD",
        expensesPYG: 650000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 400,
        utilitiesMonthlyUSD: 55,
        cleaningFeeUSD: 35,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Ycuá Satí",
        address: "Av. Denis Roa c/ Lillo",
        coordinates: [-25.2982, -57.5647],
        bedrooms: 1,
        bathrooms: 1,
        bedsCount: 1,
        parkingSpots: 1,
        builtAreaM2: 58,
        totalAreaM2: 68,
        yearBuilt: 2024,
        badge: "Nuevo • WiFi 400M",
        acceptsCheRogaPora: false,
        bankCreditEligible: false,
        amenities: ["pool", "gym", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "terrace", "elevator", "smart_home"],
        wfhSetup: "Espacio de trabajo integrado con iluminación regulable y vista abierta",
        advertiser: {
            name: "María José Duarte",
            agency: "Superanfitrión Zilla",
            type: "franchise_agent",
            verified: true,
            responseTime: "< 10 min",
            phone: "+595982654321",
            whatsapp: "595982654321",
            avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80"
        },
        description: "Moderno loft en el epicentro gastronómico de Denis Roa. Totalmente amoblado con cama queen, Smart TV 55', cocina de inducción y laundry en el edificio. Ideal para estancias de 3 a 6 meses.",
        nearbyPoints: [
            { name: "Paseo La Galería", distance: "1.0 km", time: "3 min en auto" },
            { name: "Eje Gastronómico Lillo", distance: "50 m", time: "1 min a pie" }
        ],
        images: [
            "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1502005229762-ee1b2b8ab98f?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-304",
        title: "Residencia Campestre en Club de Campo Surubi'i",
        operation: "rent_monthly",
        propType: "house",
        category: "views",
        rating: 4.99,
        reviewCount: 22,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "A 12 min del Aeropuerto Silvio Pettirossi",
        tier: "platinum",
        priceUSD: 2200,
        pricePYG: 17490000,
        currencyPrimary: "USD",
        expensesPYG: 1500000,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 500,
        utilitiesMonthlyUSD: 110,
        cleaningFeeUSD: 80,
        department: "Central",
        city: "Mariano Roque Alonso",
        neighborhood: "Surubi'i",
        address: "Condominio Club de Campo Surubi'i",
        coordinates: [-25.2155, -57.5458],
        bedrooms: 4,
        bathrooms: 4,
        bedsCount: 5,
        parkingSpots: 4,
        builtAreaM2: 380,
        totalAreaM2: 1200,
        yearBuilt: 2022,
        badge: "Recomendación del viajero",
        acceptsCheRogaPora: false,
        bankCreditEligible: false,
        amenities: ["pool", "gym", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "garden", "generator", "sports_court"],
        wfhSetup: "Estudio privado independiente con biblioteca y fibra simétrica",
        advertiser: {
            name: "Ing. Roberto Alarcón",
            agency: "Superanfitrión Zilla",
            type: "owner_direct",
            verified: true,
            responseTime: "< 30 min",
            phone: "+595981556677",
            whatsapp: "595981556677",
            avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80"
        },
        description: "Casa de descanso y trabajo en el prestigioso barrio cerrado Surubi'i. Gran jardín con piscina, quincho con tatakua, cancha de paddle, seguridad privada y generador propio.",
        nearbyPoints: [
            { name: "Aeropuerto Silvio Pettirossi", distance: "9 km", time: "12 min en auto" },
            { name: "Club Náutico Surubi'i", distance: "400 m", time: "5 min a pie" }
        ],
        images: [
            "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-305",
        title: "Villa con Vista al Lago & Piscina en San Bernardino",
        operation: "rent_monthly",
        propType: "house",
        category: "lake",
        rating: 4.97,
        reviewCount: 35,
        guestFavorite: true,
        superhost: true,
        distanceHighlight: "A 300 m de la playa del Lago Ypacaraí",
        tier: "platinum",
        priceUSD: 1850,
        pricePYG: 14707500,
        currencyPrimary: "USD",
        expensesPYG: 0,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 300,
        utilitiesMonthlyUSD: 90,
        cleaningFeeUSD: 60,
        department: "Cordillera",
        city: "San Bernardino",
        neighborhood: "San Bernardino",
        address: "Av. Luis F. Vache c/ Mbocayaty",
        coordinates: [-25.3097, -57.2965],
        bedrooms: 4,
        bathrooms: 4,
        bedsCount: 6,
        parkingSpots: 3,
        builtAreaM2: 310,
        totalAreaM2: 900,
        yearBuilt: 2021,
        badge: "Recomendación del viajero",
        acceptsCheRogaPora: false,
        bankCreditEligible: false,
        amenities: ["pool", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "garden", "generator", "sports_court"],
        wfhSetup: "Terraza con mesa de trabajo con vista panorámica al lago Ypacaraí",
        advertiser: {
            name: "Rodrigo Alcaraz",
            agency: "Superanfitrión Zilla",
            type: "owner_direct",
            verified: true,
            responseTime: "< 10 min",
            phone: "+595991443322",
            whatsapp: "595991443322",
            avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80"
        },
        description: "Villa para estancias medias de trabajo y relax a solo 300m de la playa de San Ber. Totalmente amoblada, piscina iluminada, quincho gourmet con parrilla y generador automático.",
        nearbyPoints: [
            { name: "Playa San Bernardino", distance: "300 m", time: "4 min a pie" },
            { name: "Club Náutico San Bernardino", distance: "1.2 km", time: "3 min en auto" }
        ],
        images: [
            "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1000&q=80"
        ]
    },
    {
        id: "ZIL-306",
        title: "Dúplex de 3 Dormitorios con Jardín y Parrilla en Recoleta",
        operation: "rent_monthly",
        propType: "duplex",
        category: "pet_friendly",
        rating: 4.94,
        reviewCount: 19,
        guestFavorite: false,
        superhost: true,
        distanceHighlight: "A 400 m de Superseis Denis Roa",
        tier: "gold",
        priceUSD: 1100,
        pricePYG: 8745000,
        currencyPrimary: "USD",
        expensesPYG: 0,
        minStayMonths: 1,
        maxStayMonths: 11,
        wifiSpeedMbps: 400,
        utilitiesMonthlyUSD: 65,
        cleaningFeeUSD: 45,
        department: "Capital",
        city: "Asunción",
        neighborhood: "Recoleta",
        address: "Dr. Morra c/ Andrade",
        coordinates: [-25.3015, -57.5752],
        bedrooms: 3,
        bathrooms: 3,
        bedsCount: 4,
        parkingSpots: 2,
        builtAreaM2: 190,
        totalAreaM2: 240,
        yearBuilt: 2023,
        badge: "Superanfitrión",
        acceptsCheRogaPora: false,
        bankCreditEligible: false,
        amenities: ["pool", "furnished", "laundry", "pet_friendly", "security", "quincho", "garage", "air_conditioning", "garden"],
        wfhSetup: "Habitación secundaria acondicionada como home office profesional con 2 escritorios",
        advertiser: {
            name: "Gustavo Caballero",
            agency: "Superanfitrión Zilla",
            type: "owner_direct",
            verified: true,
            responseTime: "< 20 min",
            phone: "+595981556677",
            whatsapp: "595981556677",
            avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80"
        },
        description: "Dúplex en zona residencial arbolada de Recoleta. Patio con piscina y parrilla techada, 3 dormitorios en planta alta, electrodomésticos de bajo consumo y contrato flexible sin ataduras.",
        nearbyPoints: [
            { name: "Supermercado Stock Denis Roa", distance: "400 m", time: "5 min a pie" },
            { name: "Plaza Infante Rivarola", distance: "850 m", time: "10 min a pie" }
        ],
        images: [
            "https://images.unsplash.com/photo-1598228723793-52759bba239c?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
            "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=80"
        ]
    }
];
